# Generated by Django 6.0.2 on 2026-02-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="scraper_use_email_3df38c_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="scraper_use_usernam_86c7ca_idx",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
