# Generated by Django 6.0.2 on 2026-02-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                (
                    "content",
                    models.TextField(
                        help_text="Clean article text from Jina AI",
                        verbose_name="Full Content",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Meta description or summary",
                        verbose_name="Description",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="Unique article URL (prevents duplicates)",
                        unique=True,
                        verbose_name="Article URL",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Publish Date",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Author"
                    ),
                ),
                (
                    "content_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="384-dim vector from sentence-transformers, stored as JSON list",
                        null=True,
                        verbose_name="Content Embedding",
                    ),
                ),
                (
                    "es_indexed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this article has been indexed in ElasticSearch",
                        verbose_name="ElasticSearch Indexed",
                    ),
                ),
                (
                    "es_index_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ES Index Date"
                    ),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Scraped At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
                "ordering": ["-publish_date", "-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name, e.g. 'AzeNews', 'Trend.az'",
                        max_length=200,
                        verbose_name="Source Name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Homepage URL of the news source",
                        unique=True,
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable automatic scraping",
                        verbose_name="Active",
                    ),
                ),
                (
                    "scrape_interval_hours",
                    models.IntegerField(
                        default=1,
                        help_text="How often to scrape this source",
                        verbose_name="Scrape Interval (hours)",
                    ),
                ),
                (
                    "last_scraped",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Scraped"
                    ),
                ),
                (
                    "scrape_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Scrape Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last error message if scrape failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "total_articles_scraped",
                    models.IntegerField(
                        default=0, verbose_name="Total Articles Scraped"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "News Source",
                "verbose_name_plural": "News Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SentArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="Telegram User ID"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sent At"),
                ),
                (
                    "matched_keyword",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The keyword that triggered this match",
                        max_length=200,
                        verbose_name="Matched Keyword",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Cosine similarity score (0.0 to 1.0)",
                        verbose_name="Similarity Score",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent Article",
                "verbose_name_plural": "Sent Articles",
            },
        ),
        migrations.CreateModel(
            name="UserKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Telegram user ID (not chat ID)",
                        verbose_name="Telegram User ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="Search keyword or phrase",
                        max_length=200,
                        verbose_name="Keyword",
                    ),
                ),
                (
                    "keyword_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="384-dim vector from sentence-transformers, stored as JSON list",
                        null=True,
                        verbose_name="Keyword Embedding",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "User Keyword",
                "verbose_name_plural": "User Keywords",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userkeywordmatch",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="userkeywordmatch",
            name="scraper_use_user_id_9dc6e7_idx",
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="scraper.newssource",
                verbose_name="News Source",
            ),
        ),
        migrations.AddField(
            model_name="sentarticle",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_records",
                to="scraper.newsarticle",
                verbose_name="Article",
            ),
        ),
        migrations.AddIndex(
            model_name="userkeyword",
            index=models.Index(
                fields=["user_id"], name="scraper_use_user_id_05fd62_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userkeyword",
            unique_together={("user_id", "keyword")},
        ),
        migrations.RemoveField(
            model_name="userkeywordmatch",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="userkeywordmatch",
            name="user",
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["publish_date"], name="scraper_new_publish_3399c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["source", "publish_date"], name="scraper_new_source__f95bf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["es_indexed"], name="scraper_new_es_inde_e07e07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentarticle",
            index=models.Index(
                fields=["user_id", "-sent_at"], name="scraper_sen_user_id_c6033e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sentarticle",
            unique_together={("user_id", "article")},
        ),
        migrations.DeleteModel(
            name="UserKeywordMatch",
        ),
    ]
