# Generated by Django 6.0.2 on 2026-02-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_newsarticle_newssource_sentarticle_userkeyword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="article_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Direct link to the original article",
                verbose_name="Article Link",
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="category",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="News category (e.g. Nation, Business, Sports)",
                max_length=100,
                verbose_name="Category",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["category"], name="scraper_new_categor_c9eda5_idx"
            ),
        ),
    ]
