# Generated by Django 6.0.2 on 2026-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0006_newsarticle_article_link_newsarticle_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userkeyword",
            name="keyword_aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Auto-generated translations of the keyword in multiple languages",
                verbose_name="Keyword Aliases",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="content_embedding",
            field=models.JSONField(
                blank=True,
                help_text="768-dim vector from sentence-transformers, stored as JSON list",
                null=True,
                verbose_name="Content Embedding",
            ),
        ),
        migrations.AlterField(
            model_name="userkeyword",
            name="keyword_embedding",
            field=models.JSONField(
                blank=True,
                help_text="768-dim vector from sentence-transformers, stored as JSON list",
                null=True,
                verbose_name="Keyword Embedding",
            ),
        ),
    ]
